.TH "C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/api.h" 3 "Thu Jul 28 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/api.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ARMS/lib\&.h'\fP
.br
\fC#include 'ARMS/config\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
