.TH "arms::MoveFlags" 3 "Thu Jul 28 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arms::MoveFlags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flags\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveFlags\fP \fBoperator|\fP (\fBMoveFlags\fP &o)"
.br
.ti -1c
.RI "\fBMoveFlags\fP \fBoperator&\fP (\fBMoveFlags\fP &o)"
.br
.ti -1c
.RI "\fBMoveFlags\fP \fBoperator|\fP (const \fBMoveFlags\fP &o)"
.br
.ti -1c
.RI "\fBMoveFlags\fP \fBoperator&\fP (const \fBMoveFlags\fP &o)"
.br
.ti -1c
.RI "\fBoperator bool\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBasync\fP"
.br
.ti -1c
.RI "bool \fBrelative\fP"
.br
.ti -1c
.RI "bool \fBthru\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBMoveFlags\fP arms::MoveFlags::operator| (\fBMoveFlags\fP & o)\fC [inline]\fP"

.SS "\fBMoveFlags\fP arms::MoveFlags::operator& (\fBMoveFlags\fP & o)\fC [inline]\fP"

.SS "\fBMoveFlags\fP arms::MoveFlags::operator| (const \fBMoveFlags\fP & o)\fC [inline]\fP"

.SS "\fBMoveFlags\fP arms::MoveFlags::operator& (const \fBMoveFlags\fP & o)\fC [inline]\fP"

.SS "arms::MoveFlags::operator bool ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool arms::MoveFlags::async"

.SS "bool arms::MoveFlags::relative"

.SS "bool arms::MoveFlags::thru"

.SS "bool arms::MoveFlags::reverse"


.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
