.TH "arms::odom::config_data_s" 3 "Sun Oct 16 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arms::odom::config_data_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <odom\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBexpanderPort\fP = 0"
.br
.ti -1c
.RI "int \fBrightEncoderPort\fP = 0"
.br
.ti -1c
.RI "int \fBleftEncoderPort\fP = 0"
.br
.ti -1c
.RI "int \fBmiddleEncoderPort\fP = 0"
.br
.ti -1c
.RI "int \fBimuPort\fP = 0"
.br
.ti -1c
.RI "\fBEncoderType_e_t\fP \fBencoderType\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "arms::odom::config_data_s_t::expanderPort = 0"
The port that the expander is plugged into 
.SS "arms::odom::config_data_s_t::rightEncoderPort = 0"
The port that the right encoder is plugged into 
.SS "arms::odom::config_data_s_t::leftEncoderPort = 0"
The port that the left encoder is plugged into 
.SS "arms::odom::config_data_s_t::middleEncoderPort = 0"
The port that the middle encoder is plugged into 
.SS "arms::odom::config_data_s_t::imuPort = 0"
The port that the IMU is plugged into 
.SS "arms::odom::config_data_s_t::encoderType"
The type of encoder used\&. This is used to determine how to read the encoder values 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
