.TH "arms::Point" 3 "Sun Oct 16 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arms::Point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point\&.h>\fP
.SH "Detailed Description"
.PP 
This is a helper union that defines a 2d point or vector\&. It defines a set of operators that can be used to perform vector operations more consisely\&.
.PP
A union was chosen to represent the point so that a couple different names can be used to access the same elements\&. For example:
.br
point\&.x, point\&.data[0], and point[0]
.br
all refer to the same variable\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
