.TH "arms::odom::config_data_s" 3 "Sun Oct 16 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arms::odom::config_data_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <odom\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBexpanderPort\fP = 0"
.br
.ti -1c
.RI "int \fBrightEncoderPort\fP = 0"
.br
.ti -1c
.RI "int \fBleftEncoderPort\fP = 0"
.br
.ti -1c
.RI "int \fBmiddleEncoderPort\fP = 0"
.br
.ti -1c
.RI "int \fBimuPort\fP = 0"
.br
.ti -1c
.RI "\fBEncoderType_e_t\fP \fBencoderType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This struct is used to store the configuration data for the odometry system\&. 
.SH "Member Data Documentation"
.PP 
.SS "int arms::odom::config_data_s::expanderPort = 0"

.SS "int arms::odom::config_data_s::rightEncoderPort = 0"

.SS "int arms::odom::config_data_s::leftEncoderPort = 0"

.SS "int arms::odom::config_data_s::middleEncoderPort = 0"

.SS "int arms::odom::config_data_s::imuPort = 0"

.SS "\fBEncoderType_e_t\fP arms::odom::config_data_s::encoderType"


.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
