.TH "arms" 3 "Sun Oct 16 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arms
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBchassis\fP"
.br
.ti -1c
.RI "namespace \fBodom\fP"
.br
.ti -1c
.RI "namespace \fBpid\fP"
.br
.ti -1c
.RI "namespace \fBselector\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMoveFlags\fP"
.br
.ti -1c
.RI "union \fBPoint\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.RI "Initialize ARMS using the user defined constants \fBExample 1:\fP "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBMoveFlags\fP \fBNONE\fP = {false, false, false, false}"
.br
.RI "This is a constant that can be used to specify that no flags are used\&. "
.ti -1c
.RI "const \fBMoveFlags\fP \fBASYNC\fP = {true, false, false, false}"
.br
.RI "This is a constant that can be used to specify that the \fIasync\fP flag is used\&. "
.ti -1c
.RI "const \fBMoveFlags\fP \fBRELATIVE\fP = {false, true, false, false}"
.br
.RI "This is a constant that can be used to specify that the \fIrelative\fP flag is used\&. "
.ti -1c
.RI "const \fBMoveFlags\fP \fBTHRU\fP = {false, false, true, false}"
.br
.RI "This is a constant that can be used to specify that the \fIthru\fP flag is used\&. "
.ti -1c
.RI "const \fBMoveFlags\fP \fBREVERSE\fP = {false, false, false, true}"
.br
.RI "This is a constant that can be used to specify that the \fIreverse\fP flag is used\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void arms::init ()\fC [inline]\fP"

.PP
Initialize ARMS using the user defined constants \fBExample 1:\fP 
.PP
.nf
// initalize arms
arms::init();

.fi
.PP
.PP
initialize ARMS (pid, chassis, odom, etc) using the defined constants in \fBconfig\&.h\fP 
.SH "Variable Documentation"
.PP 
.SS "const \fBMoveFlags\fP arms::NONE = {false, false, false, false}"

.PP
This is a constant that can be used to specify that no flags are used\&. 
.SS "const \fBMoveFlags\fP arms::ASYNC = {true, false, false, false}"

.PP
This is a constant that can be used to specify that the \fIasync\fP flag is used\&. 
.SS "const \fBMoveFlags\fP arms::RELATIVE = {false, true, false, false}"

.PP
This is a constant that can be used to specify that the \fIrelative\fP flag is used\&. 
.SS "const \fBMoveFlags\fP arms::THRU = {false, false, true, false}"

.PP
This is a constant that can be used to specify that the \fIthru\fP flag is used\&. 
.SS "const \fBMoveFlags\fP arms::REVERSE = {false, false, false, true}"

.PP
This is a constant that can be used to specify that the \fIreverse\fP flag is used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
