.TH "arms::selector" 3 "Tue Jul 26 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arms::selector
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (int hue, int default_auton, const char **autons)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBauton\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void arms::selector::init (int hue, int default_auton, const char ** autons)"

.SH "Variable Documentation"
.PP 
.SS "int arms::selector::auton\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
