.TH "arms::pid" 3 "Mon Jul 18 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arms::pid
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "std::array< double, 2 > \fBtranslational\fP ()"
.br
.ti -1c
.RI "std::array< double, 2 > \fBangular\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP (double \fBlinearKP\fP, double \fBlinearKI\fP, double \fBlinearKD\fP, double \fBangularKP\fP, double \fBangularKI\fP, double \fBangularKD\fP, double \fBtrackingKP\fP, double \fBminError\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "double \fBlinearKP\fP"
.br
.ti -1c
.RI "double \fBlinearKI\fP"
.br
.ti -1c
.RI "double \fBlinearKD\fP"
.br
.ti -1c
.RI "double \fBangularKP\fP"
.br
.ti -1c
.RI "double \fBangularKI\fP"
.br
.ti -1c
.RI "double \fBangularKD\fP"
.br
.ti -1c
.RI "double \fBtrackingKP\fP"
.br
.ti -1c
.RI "double \fBminError\fP"
.br
.ti -1c
.RI "double \fBin_lin\fP"
.br
.ti -1c
.RI "double \fBin_ang\fP"
.br
.ti -1c
.RI "double \fBangularTarget\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpointTarget\fP"
.br
.ti -1c
.RI "bool \fBthru\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::array< double, 2 > arms::pid::angular ()"

.SS "void arms::pid::init (double linearKP, double linearKI, double linearKD, double angularKP, double angularKI, double angularKD, double trackingKP, double minError)"

.SS "std::array< double, 2 > arms::pid::translational ()"

.SH "Variable Documentation"
.PP 
.SS "double arms::pid::angularKD\fC [extern]\fP"

.SS "double arms::pid::angularKI\fC [extern]\fP"

.SS "double arms::pid::angularKP\fC [extern]\fP"

.SS "double arms::pid::angularTarget\fC [extern]\fP"

.SS "double arms::pid::in_ang\fC [extern]\fP"

.SS "double arms::pid::in_lin\fC [extern]\fP"

.SS "double arms::pid::linearKD\fC [extern]\fP"

.SS "double arms::pid::linearKI\fC [extern]\fP"

.SS "double arms::pid::linearKP\fC [extern]\fP"

.SS "double arms::pid::minError\fC [extern]\fP"

.SS "int arms::pid::mode\fC [extern]\fP"

.SS "\fBPoint\fP arms::pid::pointTarget\fC [extern]\fP"

.SS "bool arms::pid::reverse\fC [extern]\fP"

.SS "bool arms::pid::thru\fC [extern]\fP"

.SS "double arms::pid::trackingKP\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
