.TH "C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS Directory Reference" 3 "Thu Jul 28 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapi\&.h\fP"
.br
.ti -1c
.RI "file \fBchassis\&.h\fP"
.br
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.RI "\fBThe ARMS configuration file\&. This file is where you setup everything about your chassis, including the motors, the sensors, and constants\&. This is also where you will setup autonomous selector\&.\fP "
.ti -1c
.RI "file \fBflags\&.h\fP"
.br
.ti -1c
.RI "file \fBlib\&.h\fP"
.br
.ti -1c
.RI "file \fBodom\&.h\fP"
.br
.ti -1c
.RI "file \fBpid\&.h\fP"
.br
.ti -1c
.RI "file \fBpoint\&.h\fP"
.br
.ti -1c
.RI "file \fBselector\&.h\fP"
.br
.in -1c
