.TH "C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/chassis.h" 3 "Tue Jul 26 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/chassis.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ARMS/flags\&.h'\fP
.br
\fC#include 'ARMS/point\&.h'\fP
.br
\fC#include 'okapi/api\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBarms\fP"
.br
.ti -1c
.RI "namespace \fBarms::chassis\fP"
.br
.RI "The chassis subsystem\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarms::chassis::motorMove\fP (std::shared_ptr< okapi::MotorGroup > motor, double speed, bool vel)"
.br
.ti -1c
.RI "void \fBarms::chassis::setBrakeMode\fP (okapi::AbstractMotor::brakeMode b)"
.br
.ti -1c
.RI "void \fBarms::chassis::resetAngle\fP (double angle=0)"
.br
.ti -1c
.RI "double \fBarms::chassis::limitSpeed\fP (double speed, double max)"
.br
.ti -1c
.RI "double \fBarms::chassis::slew\fP (double speed, double step, double prev)"
.br
.ti -1c
.RI "bool \fBarms::chassis::settled\fP ()"
.br
.ti -1c
.RI "void \fBarms::chassis::waitUntilFinished\fP (double exit_error)"
.br
.ti -1c
.RI "void \fBarms::chassis::move\fP (Point target, double max, double exit_error, double lp, double ap, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::move\fP (Point target, double max, double exit_error, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::move\fP (Point target, double max, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::move\fP (Point target, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (double target, double max, double exit_error, double ap, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (double target, double max, double exit_error, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (double target, double max, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (double target, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (Point target, double max, double exit_error, double ap, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (Point target, double max, double exit_error, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (Point target, double max, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::turn\fP (Point target, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::tank\fP (double left, double right, bool velocity=false)"
.br
.ti -1c
.RI "void \fBarms::chassis::arcade\fP (double vertical, double horizontal, bool velocity=false)"
.br
.ti -1c
.RI "void \fBarms::chassis::init\fP (std::initializer_list< okapi::Motor > leftMotors, std::initializer_list< okapi::Motor > rightMotors, int gearset, double distance_constant, double degree_constant, double slew_step, double linear_exit_error, double angular_exit_error, double settle_thresh_linear, double settle_thresh_angular, int settle_time)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBarms::chassis::maxSpeed\fP"
.br
.ti -1c
.RI "double \fBarms::chassis::leftPrev\fP"
.br
.ti -1c
.RI "double \fBarms::chassis::rightPrev\fP"
.br
.ti -1c
.RI "double \fBarms::chassis::slew_step\fP"
.br
.ti -1c
.RI "std::shared_ptr< okapi::MotorGroup > \fBarms::chassis::leftMotors\fP"
.br
.ti -1c
.RI "std::shared_ptr< okapi::MotorGroup > \fBarms::chassis::rightMotors\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
