.TH "C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/chassis.h" 3 "Sun Oct 16 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/chassis.h \- This file contains all of the functions and variables needed to control the chassis\&. Look through the documentation \fBhere\fP for more information\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ARMS/flags\&.h'\fP
.br
\fC#include 'ARMS/point\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include '\&.\&./api\&.h'\fP
.br
\fC#include 'pros/motors\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBarms::chassis\fP"
.br
.ti -1c
.RI "namespace \fBarms\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarms::chassis::setBrakeMode\fP (pros::motor_brake_mode_e_t b)"
.br
.ti -1c
.RI "bool \fBarms::chassis::settled\fP ()"
.br
.ti -1c
.RI "void \fBarms::chassis::waitUntilFinished\fP (double exit_error)"
.br
.ti -1c
.RI "void \fBarms::chassis::move\fP (std::vector< double > target, double max, double exit_error, double lp, double ap, MoveFlags=NONE)"
.br
.ti -1c
.RI "void \fBarms::chassis::move\fP (double target, double max, double exit_error, double lp, double ap, MoveFlags=NONE)"
.br
.RI "move the chassis a target distance forward "
.ti -1c
.RI "void \fBarms::chassis::turn\fP (double target, double max, double exit_error, double ap, MoveFlags=NONE)"
.br
.RI "turn the chassis a target angle "
.ti -1c
.RI "void \fBarms::chassis::turn\fP (Point target, double max, double exit_error, double ap, MoveFlags=NONE)"
.br
.RI "turn the chassis to face a target point "
.ti -1c
.RI "void \fBarms::chassis::tank\fP (double left, double right, bool velocity=false)"
.br
.RI "move the chassis using tank drive "
.ti -1c
.RI "void \fBarms::chassis::arcade\fP (double vertical, double horizontal, bool velocity=false)"
.br
.RI "move the chassis using arcade drive "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBarms::chassis::maxSpeed\fP"
.br
.ti -1c
.RI "std::shared_ptr< pros::Motor_Group > \fBarms::chassis::leftMotors\fP"
.br
.ti -1c
.RI "std::shared_ptr< pros::Motor_Group > \fBarms::chassis::rightMotors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains all of the functions and variables needed to control the chassis\&. Look through the documentation \fBhere\fP for more information\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
