.TH "config_data_s_t" 3 "Sun Oct 16 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_data_s_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <odom\&.h>\fP
.SH "Detailed Description"
.PP 
This struct is used to store the configuration data for the odometry system\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
