.TH "C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/lib.h" 3 "Sun Oct 16 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/lib.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ARMS/chassis\&.h'\fP
.br
\fC#include 'ARMS/flags\&.h'\fP
.br
\fC#include 'ARMS/odom\&.h'\fP
.br
\fC#include 'ARMS/pid\&.h'\fP
.br
\fC#include 'ARMS/point\&.h'\fP
.br
\fC#include 'ARMS/selector\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
