.TH "C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/pid.h" 3 "Mon Jul 18 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/pid.h
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBarms\fP"
.br
.ti -1c
.RI "namespace \fBarms::pid\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDISABLE\fP   0"
.br
.ti -1c
.RI "#define \fBTRANSLATIONAL\fP   1"
.br
.ti -1c
.RI "#define \fBANGULAR\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::array< double, 2 > \fBarms::pid::translational\fP ()"
.br
.ti -1c
.RI "std::array< double, 2 > \fBarms::pid::angular\fP ()"
.br
.ti -1c
.RI "void \fBarms::pid::init\fP (double linearKP, double linearKI, double linearKD, double angularKP, double angularKI, double angularKD, double trackingKP, double minError)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBarms::pid::mode\fP"
.br
.ti -1c
.RI "double \fBarms::pid::linearKP\fP"
.br
.ti -1c
.RI "double \fBarms::pid::linearKI\fP"
.br
.ti -1c
.RI "double \fBarms::pid::linearKD\fP"
.br
.ti -1c
.RI "double \fBarms::pid::angularKP\fP"
.br
.ti -1c
.RI "double \fBarms::pid::angularKI\fP"
.br
.ti -1c
.RI "double \fBarms::pid::angularKD\fP"
.br
.ti -1c
.RI "double \fBarms::pid::trackingKP\fP"
.br
.ti -1c
.RI "double \fBarms::pid::minError\fP"
.br
.ti -1c
.RI "double \fBarms::pid::in_lin\fP"
.br
.ti -1c
.RI "double \fBarms::pid::in_ang\fP"
.br
.ti -1c
.RI "double \fBarms::pid::angularTarget\fP"
.br
.ti -1c
.RI "Point \fBarms::pid::pointTarget\fP"
.br
.ti -1c
.RI "bool \fBarms::pid::thru\fP"
.br
.ti -1c
.RI "bool \fBarms::pid::reverse\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANGULAR   2"

.SS "#define DISABLE   0"

.SS "#define TRANSLATIONAL   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
