.TH "C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/point.h" 3 "Tue Jul 26 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/btdav/Documents/COURSES/SIGBOTS/SOFTWARE/ARMS/include/ARMS/point.h
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBarms::Point\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBarms\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Point \fBarms::operator*\fP (double s, const Point &v)"
.br
.ti -1c
.RI "Point \fBarms::operator*\fP (const Point &v, double s)"
.br
.ti -1c
.RI "Point \fBarms::operator/\fP (const Point &v, double s)"
.br
.ti -1c
.RI "Point & \fBarms::operator*=\fP (Point &v, double s)"
.br
.ti -1c
.RI "Point & \fBarms::operator/=\fP (Point &v, double s)"
.br
.ti -1c
.RI "double \fBarms::dot\fP (Point &a, Point &b)"
.br
.ti -1c
.RI "double \fBarms::length2\fP (Point &p)"
.br
.ti -1c
.RI "double \fBarms::length2\fP (Point &&p)"
.br
.ti -1c
.RI "double \fBarms::length\fP (Point &p)"
.br
.ti -1c
.RI "double \fBarms::length\fP (Point &&p)"
.br
.ti -1c
.RI "Point \fBarms::normalize\fP (Point &a)"
.br
.ti -1c
.RI "Point \fBarms::normalize\fP (Point &&a)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
