.TH "The" 3 "Sat Aug 27 2022" "ARMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
chassis subsystem\&.
.PP
This namespace stores all functions and motors used to control the chassis\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ARMS from the source code\&.
